name: gg_clone_dependencies
description: Tool that clones all dependencies of a dart project to the current workspace
version: 1.0.0
repository: https://github.com/inlavigo/gg_clone_dependencies.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  path: ^1.8.0
  args: ^2.6.0
  gg_console_colors: ^2.1.4
  gg_process: ^1.1.6
  gg_args: ^2.0.4
  gg_log: ^1.0.6
  gg_local_package_dependencies: ^1.1.2
  gg_project_root: ^1.0.4
  pubspec_parse: ^1.3.0
  yaml: ^3.1.2
  mocktail: ^1.0.3
  http: ^1.2.2

dev_dependencies:
  gg_capture_print: ^1.0.9
  lints: ^4.0.0
  test: ^1.24.0

executables:
 gg_clone_dependencies: